<template><section><div class="d-flex justify-content-between align-items-center"><div><h1>Notifications</h1><p class="text-muted">Queue notifications and update their status.</p></div><button class="btn btn-primary" @click="showForm=!showForm">{{showForm?'Close':'New notification'}}</button></div><p v-if="message" class="alert" :class="ok?'alert-success':'alert-danger'">{{message}}</p><form v-if="showForm" class="card p-3 mb-3" @submit.prevent="create"><div class="row g-2"><input v-model="form.template_id" class="form-control col" placeholder="Template UUID" required><input v-model="form.user_id" class="form-control col" placeholder="User UUID" required><input v-model="form.event_type" class="form-control col" placeholder="Event type" required></div><div class="row g-2 my-2"><input v-model="form.title" class="form-control col" placeholder="Title" required><select v-model="form.channel" class="form-select col"><option>IN_APP</option><option>PUSH</option><option>EMAIL</option><option>SMS</option><option>TELEGRAM</option></select><select v-model="form.priority" class="form-select col"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></div><textarea v-model="form.body" class="form-control mb-2" placeholder="Message" required></textarea><button class="btn btn-primary">Queue notification</button></form><div class="card p-3"><BaseTable :columns="columns" :rows="rows" :loading="loading" row-key="notification_id"><template #cell-status="{row}"><select :value="row.status" class="form-select form-select-sm" @change="updateStatus(row,$event.target.value)"><option v-for="status in statuses" :key="status">{{status}}</option></select></template></BaseTable><button class="btn btn-outline-secondary mt-3" :disabled="loading||!hasMore" @click="load(page+1)">{{hasMore?'Load more':'No more notifications'}}</button></div></section></template>
<script setup>
import { onMounted, ref } from 'vue'; import BaseTable from '@/components/common/BaseTable.vue'; import { get, post, put } from '@/services/api'
const rows=ref([]),loading=ref(false),page=ref(1),hasMore=ref(true),showForm=ref(false),message=ref(''),ok=ref(false),statuses=['PENDING','QUEUED','DELIVERED','FAILED','READ'],form=ref({template_id:'',user_id:'',event_type:'SYSTEM_ALERT',title:'',body:'',channel:'IN_APP',priority:'NORMAL'})
const columns=[{key:'title',label:'Title'},{key:'full_name',label:'Recipient'},{key:'channel',label:'Channel'},{key:'priority',label:'Priority'},{key:'status',label:'Status'},{key:'created_at',label:'Created'}]
async function load(next=1){loading.value=true;try{const result=await get(`/admin/notification?page=${next}&limit=20`);rows.value=next===1?result.data:[...rows.value,...result.data];page.value=next;hasMore.value=next<result.pagination.total_pages}catch(e){message.value=e.message;ok.value=false}finally{loading.value=false}}
async function create(){try{await post('/admin/notification',form.value);message.value='Notification queued';ok.value=true;showForm.value=false;await load()}catch(e){message.value=e.message;ok.value=false}}
async function updateStatus(row,status){try{await put(`/admin/notification/${row.notification_id}`,{status});row.status=status}catch(e){message.value=e.message;ok.value=false}} onMounted(load)
</script>
