<template><section><div class="d-flex justify-content-between align-items-center"><div><h1>Templates</h1><p class="text-muted">Create and activate notification templates.</p></div><button class="btn btn-primary" @click="showForm=!showForm">{{showForm?'Close':'New template'}}</button></div><p v-if="message" class="alert" :class="ok?'alert-success':'alert-danger'">{{ message }}</p><form v-if="showForm" class="card p-3 mb-3" @submit.prevent="create"><div class="row g-2"><input v-model="form.event_type" class="form-control col" placeholder="Event type" required><input v-model="form.default_channel" class="form-control col" placeholder="Channel" required><input v-model="form.title_template" class="form-control col" placeholder="Title template" required></div><textarea v-model="form.body_template" class="form-control my-2" placeholder="Body template" required></textarea><button class="btn btn-primary" :disabled="loading">Create template</button></form><div class="card p-3"><BaseTable :columns="columns" :rows="rows" :loading="loading" row-key="template_id"><template #cell-is_active="{row}"><button class="btn btn-sm" :class="row.is_active?'btn-success':'btn-outline-secondary'" @click="toggle(row)">{{row.is_active?'Active':'Inactive'}}</button></template><template #cell-template_id="{value}"><code>{{String(value).slice(0,8)}}…</code></template></BaseTable></div></section></template>
<script setup>
import { onMounted, ref } from 'vue'; import BaseTable from '@/components/common/BaseTable.vue'; import { get, post, put } from '@/services/api'
const rows=ref([]),loading=ref(false),showForm=ref(false),message=ref(''),ok=ref(false),form=ref({event_type:'',title_template:'',body_template:'',default_channel:'IN_APP',is_active:1})
const columns=[{key:'event_type',label:'Event'},{key:'title_template',label:'Title'},{key:'default_channel',label:'Channel'},{key:'is_active',label:'Status'},{key:'template_id',label:'ID'}]
async function load(){loading.value=true;try{rows.value=await get('/admin/template/getAll')}catch(e){message.value=e.message;ok.value=false}finally{loading.value=false}}
async function create(){try{await post('/admin/template/create',form.value);message.value='Template created';ok.value=true;showForm.value=false;form.value={event_type:'',title_template:'',body_template:'',default_channel:'IN_APP',is_active:1};await load()}catch(e){message.value=e.message;ok.value=false}}
async function toggle(row){try{await put(`/admin/template/${row.template_id}`,{is_active:row.is_active?0:1});await load()}catch(e){message.value=e.message;ok.value=false}} onMounted(load)
</script>
